### ISSUE TITLE
Form changes can lead to a lost of a custom pictures configuration

### ISSUE THREAD

**Issue by gillesdubois** [itsmng/formcreator#13]
**Describe the bug**
Form changes can lead to a lost of a custom pictures configuration

**To Reproduce**
1. Go to 'Administration > Forms'
2. Set a custom picture 
3. Save
4. Go to 'Administration > Forms'
5. Change an unrelated fields (comments / name of the form for example)
6. In some rare case, the link to _pictures is changed to a fake inexistant file 

**Expected behavior**
Not loosing custom pic config on form data changes

**Screenshots**

![webinfo](https://github.com/itsmng/formcreator/assets/9396603/035ee1cf-9953-4bee-b639-35a39c8889a6)

![image (1)](https://github.com/itsmng/formcreator/assets/9396603/11c1abdd-74f1-4455-beff-93c2ff0311f4)

**Comment by AntoineLemarchand** [comment]
fixed by #14
